### ISSUE TITLE
这不是坑爹么，实际实现效果也太差了吧，楼主。

### ISSUE THREAD

**Issue by RoyWallace** [north2014/MusicView#1]
效果差的太远了吧

**Comment by cpoopc** [comment]
看了这个我脑海中浮现了四个字..江湖骗子

**Comment by microstudent** [comment]
UP主都没放上真正的效果图=-=。
本来想好好学习绘制类似液体的合并效果是怎么实现的。下载代码一运行发现界面和想象中的有点差距。而且动画好像有点问题
设备是三星的，Android是6.0。动画无法运行，不开issue了
